# include <iostream>
# include <vector>
# include <unordered_set>
# include <unordered_map>

using namespace std;

class Solution
{
public:
    int countPalindromicSubsequence(string s)
    {
        vector<int> first(26, -1), last(26, -1);
        unordered_set<string> palindromes;

        // Track first and last occurrences of each character
        for (int i = 0; i < s.length(); i++)
        {
            if (first[s[i] - 'a'] == -1)
            {
                first[s[i] - 'a'] = i;
            }
            last[s[i] - 'a'] = i;
        }

        // Count unique characters between first and last occurrences
        for (int i = 0; i < 26; i++)
        {
            if (first[i] != -1 && last[i] != -1 && first[i] != last[i])
            {
                unordered_set<char> uniqueChars;
                for (int j = first[i] + 1; j < last[i]; j++)
                {
                    uniqueChars.insert(s[j]);
                }
                for (char c : uniqueChars)
                {
                    string temp = "";
                    temp += (char)(i + 'a');
                    temp += c;
                    temp += (char)(i + 'a');
                    palindromes.insert(temp);
                }
            }
        }

        return palindromes.size();
    }
};

int main(int argc, char const *argv[])
{
    Solution sol;
    string s = "swnmktiziarhdvsbqottoksakebbtpzxaevptnqronedeszuugctxnvigkhasprrzcuyhzpahupkajeqvlagpezgxthuvsusvbscmwaqyhfcwnwtxcqguxrxrcayucbpeqbwfnonxybedeyoquvviyradnpioqmhbokpcpxwemkaadaqlquzkrwhfujqqinvmaethrrhrjkacyylgexokvsgjtaxhjdtrbjslncnljyrzwvhwndjslmnhskzygakmuzkpdpomxxxdbgpkekqakblypexjzxyrexpyofttwknslexlhgnbyuxvcfnetczkaxhbzsydqtbutrwwtofdfvmdqodpoqvjeuydxizqbeigomlpuqgxkxozuxzazjnwcrgylkcnozdtxquwagymdefbfrikammqbzjfcorzdiqvpbfmfbhehzhloahllykdfzxxrmiupuqzrwzcsyenjgjzavojajtsvivgsqrgrxbmmbagvaixdhatpuoeuafjtttbnxokyqsalodipizjrsffgsdbezhwnnbtlbspmzpbrdscvvqzwcfwdkcihibekedpkhlrzdipmamhshsybnxuxxcthtvosokuuzdkgsoxjzdjthdmolfkkivkbklabtxcqgaodwppzbtqddpirtljmpgcqekbsldzjvmhivzpditzhhindaospjjfxvtkkwprdmmikazkvviklhwekxafubnajfalrqcmcljlbdgbgilgsztjcvszmbsdycqnokzywkfixofipgrloarbegtmmtogaqoeplgevrpmudowhbwxitvyxlqpeemgyeswqbgeogzbqfunhfhrpnxariicvrdkxllrqfydavuzfeulquxmmfykssakysauaobjapenhqcvquhbxhrwmtnlkjyvlevgkurjwvkygkbogpqfnfpurtvsvpcpslpqiiwpufvulfdfpxccspynqrxihyfaseltzwdfpnxyhvyeklnmwunxdlqqbrzhkbszfsojhtonwharnrqoufrgaqxekdvbwkjdcixtrkhmyyitjmczglabniukndrjkjiexwgupmhdwfnxzauvvwslykbqvgxnkeuibpnapwtfrauqvmmvvomvidgfkhaibftjrhnzomqfgaivtbrleqhqvbgcxptihvaeibctrmnlpycinlgxneansviqwsuhoeqfzltjostekmyfwlsjeprqrjznxtmnhdjjiiqpakddsfmlnpzwfroavtlvwsqlrovzpsbukifnzwoqblfnjbmbpjztqevfgnknwyrkdpreyupqicwoeounkrtndvqmxktzadldmdokpghsrwrplbsbmlpwuwzejlulttvrwciqrtlxjqnqrtnshbjnfziimbxcdfqibkzcqkynbaqwllbwgzuqjngzohxzvlwyvbfdifmrwjyjsexrrgnzufaocoxrqzfecwtbjtnpuamfhjmgedtooqxmtyplliyxbrkoqyxcuhhmsbpvfmlazpsdkrzzuadzqztoqjvdxkldtzkyaztxhvxdwdrzgpbxfllfkjtcwpiqhkhaegwbhkjwdvvcjmdfoujxjpipeerjwvhbfwuviztibsfyzuygomexfamgggjjtcrhvdcgulnpibwaaigmlcfsunbsnzcfccbfmkqyauclbrqihilbqqawvrgvbyetaaebyliqyxaivetcuakaigtoazkxftdddazgzdrbjrcrpbbtghfcfeejzuetgvkhdhnhuplagnlgtspjllrqwgroqemgkuiejyjiwgtkeuwnqkhgujgwsewuyyksriossktwoxtefxtkydcmelqyytofhyhonlrauknhmqqttuccwrncxnfmaaumjmevacnlmosodtodzzkftuleqvtzqksikxecdywpxakonrzcqsjhlqlrkxfipaycjuaksohptcfhhmrvrfrncbougsywmfbgocahrprubixexdowwykoazwpgdyugxyhgebibbmzcvycxjcucscmfdspiwadxraznuccdnwhdmsupzmnmhlpgucxmpczdphgdjwbgxfbplrkkgieitmibdjmvymoshnxlpnzpzaczsilyxfjnxweqcektjjgwmrcwrhvavnykebslvwaqvkprzucddmencjuefoeohnmwnjppahbtgpdjusyjawufzyyeqpyayhqyjmzpmgdowahqxsihpwdttcrhouhwdacnopafizosazmpddfrssgxgspavoyxuphtohotvplqrjdpoabbilgtjxcilcfrbpodfahmkpqwhhumxiwahetxehaacsisiykcnihyyjvojeelgtfdurhefcqxdkbavpkxrplcheddhkotxjgekpmzafdjafvpnhuvadkrboqfqmmpaqepicdvjshmnjzispqxfhuszdgzqmxnbihtvludhtfpxxrzlklbemxkduecsiokbsbdbcmoyaqmlidfmopbdvnhnkxchdiaatlixonxdgsfgirnjpdmzscrfrkowifnbchwvuelhlwwwjumziizxmvritpzglhlevpsvakdakdoinicvbkdlkmpgialugwwbohwrxeuhmowyssaxzsmwjwhrlfqnclryzdgltebosiskksafqrwuvlabdudvvxsnngkgzoftkloauezoksqsjwqgxxwpazxhsbwdqtcofbqxacikmunrsbwfnnqsagbhhbkxirveqcnfiinfqaxnihcvlgcyaxurkpsqfslcnkznkcovkjtnrebwswizfejopkldjjggrunhkrcxsibroglopfvuauievetloqgbjtbiwjhcgumexnomxvqtfwvyumxydwnddtqxfublcbvshfrmxzjrwrlmtvuxyrpmjsluklhpsjwfuapjevhdrrjuqyevptgqaasmgbcmqcxitcbsxkaakosrvxpwxfinsjxpcomcggxnkqwrgewczmdrldniogxxzmdavrtrakbhtuipoifdwkqswsfgxvxjsvfaxbabvpblcaywnbnzfshiwperqfysqkcuknqnvddqnjzthlsglajsbvzajofugwlypqhdoztdkgztjaskmmwnmwdnvfylnrjcrwueyeellnrasfqckveoqrszahpvociqmdipmhoeoyniyxyhucykmpoydywwjcnccznbwjbsehseyoxjmbgadfdtdqbnvahozkqizewkfdojxayqadgeksdsojmuqzsiwruthyyjkumbjxujhyfibjlonvjwftgfhtfyjolekmlkhiewvmnanpguqupfvggzlpinjtuibzaegmtalhxttoslxmdziqxrzaoakizcadsazaeoiixdmgrrgfmwteuscdrohwkelgovjercbjffsjhygtzuvqpicryijtflatdevkflkzdcimzstttgctagdzrkaqbocvgugqibtyiaiqpdvxskfuyyfuvnoyiiyrqbjvkjwdescgmtlmpbshahgxnsqgwjxcaqezmdqikrcrmdxyvxfeclrcbnfqepgobiflucadnlaqjpqsjfgiazaujugmpxtijbpnlkguhpsfkrrhbsduocbgodebtcgjcidcnojgaoftwrnsqfvgorcymgjatphmmbadgsuzxllgjuurvielnccutquhgjpdkivplmglrdtnkdlpkdkvylfajfcowmhzedrythjbhkjmffhrblurerjhfpztfygagioopxyfougaompqkfvtoeyusycqmbifbxbtrpcldemnanlpzkbvilpusrvmhpqbewcdhwuzjtoncyzlmqryskgzfcpzjjvttcppfxncvfwsqxbnyscfvmlmerekurkdvbpngawipbmejhnifsxvgpptdmhtpexuxcvbptiwbtzygmkeyvzskaskoggvsoickupaumkriybpshwpmqxazpwslqxiyyknbfzmylmdmfhaxhqqtycqwvfvkxegixcoqighzwhrrehvtapljxcrnrzkhpocmfosxmivdvzrqnvkbxuafjqepzaygjjpyleejgjocbvuervuuhhqdaletheurofgfjytjxgalvvegojqdiagivpjzwqyuzpwxvwglxwkiicwkblunatuidnlyztpkjzlppgaslwqwwlbwqxczfnuyylimjliqbskacmhosehfzpqlnazyixquksufibvtgeobvneilhadbwwowzlejvnuqtgqotkobkijavactlppcuqahxwdwslntbfidytfhhqgnptsgnrdflkmvxlfdlhjmlrxkylibpxxpvgmujhhghnipwllgvatgkkmawawkjilfcimfubpuqbwtujjnghggzurkgyxwdkzqxraygaztbtvptjkcrpotvzccxntlykbsmlcqqnrhmpkqujxsajdkzpaqbssraesmxwivrqkxbbbwnjihwfpcltighhdephaxwesumfjcxrtkiwmhfzxbrajjgykivjyyujedoiwubphxubezziuvzcltenycfnycxttzybgkgszexcpjmvzwvtcbimfccscgiqjwyibbhalcsxqxkphtikvlthzhutepdywpibhcqtckcsjqrcbtvsndrdtkdvydcvjqeuvojdnqmustaoduqyqmtolseayrxgimduoydjhesbrnyqsdqnajhauvgkjhmluspisawqzpikrfckqjufonylwjsxpvbkykdyvaccsfjxmprlwtqfaitswnutsoyoiptgvtyglopwykfbosdsmvgnnvnuvirdxjrrrwexsxtcfgflninhykxqnpkiomghioicjfyiiuiqysmnlhzbqzkxylidtdqmgfpjitulxplpgsxbyjnevkeatimqehdhothrejoongrbcqnaafxobwwlgunktcigkagekplwyvksmbifywhocrsvjlqrujbzwyzswqrowrlwoceegyjmnhklpvvvcuoocnljborhupefcxqettnqrmlljixmjhpqsqhzlmmikoysvgpxmyshcfpmzrcyqmwtpgrvrsmeymnkciqtmcnwjfrdwnzjautuvmpvjnqkexnxqdfeftuqlhmguzlsgzrmvvghosoznfyjtalevccjrrbctyluhaosenicxetjvgouplrjflzjrjnkmldnhcfuvtpbepximiplwxissktwygzftzrrxrfjqvodvnziyrgsvysudntkycvryuegriejypuoudiqhztlgqjjfjvhyccunwxifxezrdfvqcplylhcuhmcjdabrgggbceefkfnwkhxbozrmcoujtjmrrbkymbovkbhnvffvevruglhpcasrfrkxuozstqfdvzsprdbwockopmahdigpqkdwykaelttonjhawygujgnhrqcklxicixjfriaecbvcxgcinqsoafvwlmmwseinxxhdxsackogqoigkgtlvlwlbkfiyvyulqvvqmgfepkvsitmzziuhhnbhwluvozkwvebpwxjpxukdcmzmhlhtklnudkohiyrtppgrnjkvjppxyskfdkoatlllpmtfovdfmettlrcytzdokeukzqefgrubdqygjuvxvyjzgfxkidinkupcngsbuwgnvinuiczqtnaejiduizkzzjumwyoqlkrbsyegbmxczxozxyuromnmxnfubuuouevmrkhlgtonmacbnirdarsrasmhybhmdwbwgkwitujkrlhvfsbnthoyeaznmxrfnqluwizddmgrisqlcbclpwmdqjobwesjgszlagqfmiexizqjidlfplheauiyhwzzxhvvpedpnoseqyzxsgylumwgehqihxnezjmikshxwqvpotfyqqdmwyqsoabsmmdwkszvdgdakpbtsgvzxrdgyclvkxgyiouwqndpfzpzhueoqvzqikksuucjwaelxtmukasdoosqlvkwqhlmvsirbxegkmdsblyvgoqhgophwtrwuremsifvvcfamhgxrbzlcehmgqoevegjibbgdcasjjnmuygzbdxvrykbpevwdguamnpvvtxxjtsiyyzqwcrwimdylfyqdhgvltdwrwrxsgdwalbbdiokvrklwhrskxntpcchttwtpmnncpauxrkgnknstcvjkpzqrjztnemnayseaqoryheffkanssanbklwtpzjqjhokxgmoyjnkjwimcljbruvfhycbqlpdsdnyltfusmgrcmocuvchmdwdrdjviabipazsrpofwklnmicffuhnubacfehyzmzhlozkzkknmfcpjdeuqbegdxhjtlwyecjobgxwewwabkbocepmoumppjfcdkiovwhedugogoksglmhbyvwxadrqvxupgoacgyuwotvvuqtwjrpxskouhzfcctncwwqiyicseqlpaibjatuuxlhvlfacvjxhmydizpulgfwygqpxnaygcftzheqzbvaetlgbqbmygraankikcikkhblykpwjqpnhgbaqkczxlmtlytfmoiffzancxlotvzhaxghyviplfgrhoksiyfzmrvsjxwtispeqzfkctmvgzfohlxhmsyftojnwzgqwrklcszyhfdtxkyljocwvmdwddasppyjghfpslchzqjawpgrmvcokypdipwbaykbbcyvrtcibbpfgguqndcgbtnrfwrjobryxvwmfybggdrymqqkxjikpdbzowafcskhmbqzfaegdqplexpbwlagfpbofeiunxqklcjplgvoveeeptgrhyutlsonwwbufbgpnimcisprsuxsemmpejcdsgkgekxzkadihnaqiqomuszufvzwijoqdshcbrzzlfndjymlcjosefuojyayspegqdmzvecxrnfelszthjemaqvodmvbreplxqietiirayxachngdlerakzdgatnaxrrwqfluoztdyapwsfkxlkoshgwghgyklgmaohtocsckdyveadcjiapupzktudvsjssduobnozqqgxtywhzeiwfjucxuvirvmsoebclnaggzunuatmvluwixezfyirhtpeiuollpzcruzufstmzlgtrckozwzoxbtwrzeufspjanhltdnpnqfrxhxttsotmwvdcxikbuwfrtwrwdjqywnncuggokgsxaagpqzwyqhhmxrwiczlpvtdqyhgtvzckytgpxfpiqsobvsolninfrirubmivzrmyfzqcrmycxqfrqanfpdfsiaxkpiyitsftzyrkfliridqepbddgmhuiagjjszbzakmbkiyuouuceogrcqmtuvilkxedzqrqjhksgagjviidkslmmouiugdkzopgvansvkjrvdyxoerdojiacuaqxasyrebpfialmecebqrtvpqvtexupcwfmexbbownqlhlbhomoxuxybfervtaczkobhkknithkvksalvgeqxzellmgmxglvshimubldpnlxoenududksstglafmqyaksoafrzkhmwvqdpedetgojzrhvucpzogalydanskwcemqsbvbflojljsqhcbzcyoarbcojsabjhmryfreczexmxumqrrwifpiwztgtjjrqtrehkcufhyuwcxelupflltturlntxtanitvlpbjhsnchpnfvikhbjgioplejgdlpcdrbsjsbnklnozifegvknfvlsqswatxdwgjzmyawhvvnwmuwsdbthzgshhaeglcsxrzwcllmnvidvelylxnqpolmhiglhbhdpzsprfzxrzlsizzpgxnadhzhhpkujdxzkuddxwbymrigaigjddqhgflrvxsxbkqhlwkwucqfsmwomtbkcshqnnjjivcyewredyxnolbyvpkxptenesnhwibcfrvowlutetxfljlhuytodysuedmjagazmovlctkrffqjwtysmilfqwwlqtbiijpfyufqveiylxiegtziixnssfplxlbckznyjpqwkqgkuwjazhrxtltfsqbrhpjmrarlergivrhehmaoibdsfyoadsnctdfjobxozaryjflvfkaqletbijprjspxjmopjjxiqrkoqlhjxvxoqyrdwxdyyxuqnubqcbqehxmsibfurmkqgfnudyesrgscezwhtefugquagesvxjvemioshvpgdxgehaopyufhzzgnjbftqrxlkegvddaecsfcfcphaqybonbjkvedorwaerekovfldtwqmzzssbmarrxccnthiwcsuaxgygjamgnuivmjsjwlfvtfkvrynbqwttixtzzytojubkmaphxwzkpwdtflacrnaamxhbkgffatinmhssoqqgitvmdwiosroihiwfuxyuzxnetloxomkoqdgagggjikuntygkmcbflielkdjhncugclosssxbodhxwwbnetaiiqjjgtngngwuvglzufwrqizwjklazwcyqdmdfnumgdcwzlwfugjubpvqaufasokxjobksgxuahnghwyvaremosowdvpjhtlidctsvsjlmeaakyxxsbzfhpusieidkffehtpsrrbcaoydshrlytgwwuyhhswesqxgsuuxxffenmjkmzdfxkihlsccndszvwyyrnpbsasdzdhkgsccpnbojhthxftunoqisgzrzovslboxqieyetsoaztkopprkaojsfzvqjbhtrdcsvezmvtvabgnbqtksttyfauusoxnhheslsowyekbmhwvkllkrcpeczhmjwufiddezkzffvkygeyyfaxtzlugttfcnddmtjdsftozbuvwkykyfmfzdnjkuugduwfretfavsvtsbopdfyatafgtrqnvfhktcjmoxhfcnsqtrcyokazqhvjhvdjrofqehisqlqzpnjfsdzfuapppxrnffsaepjprzuursdalwtnqtklzmmwvpngojqxanedmecjtgrhozfppxhfoitklrjbbmadwadumfrftetrlsveshngfzlkupaaolsstfweiyltxqfmjjyczuuqafckxurjychtvskyvgmfyglobuxsdyailxceoxtlpxoglggbvnqnktbgnoprhuyeyhwjnpecvrkvnbnbiiqjahufklltprwledizgorszoknyboqbvdnffdosravniaweiwfncwaehjmzcjbtrchopekujwiortpvonclrbaaiypfevyosuyjmxckdpfdthjzbwwvbbzfwbymnjelokcrxzxutsqxzpvylmccobqoxrdrqfrvyfejwnmsdldchrporszvvwsqokozjicdbfknkhcroagukbobpxguoglihwakpvtvxavslilorqxjrmdzcdqaqlwqxewrqhkkcpibkwhdzkmhsxixdurduyctktoltinhywpqukqdjemmrbbjyyfsddefdvkantnqpwlcybuajtffc";
    cout << sol.countPalindromicSubsequence(s) << endl;
    return 0;
}